### ISSUE TITLE
Does this boot from µSD or flash

### ISSUE THREAD

**Issue by keiem** [Ruka-CFW/s30-cfw#2]
Hello,

Thanks for making this firmware.  When I build this, do I need to run it from µSD or do I have to burn it to internal flash?

**Comment by acmeplus** [comment]
The system currently runs as an overlay on top of the existing firmware. It does not build a full firmware but just the rootfs. We are in the process of doing lots of changes and documenting the build process, so while it's possible to compile and run this current repo, it would be better to wait until the compilation & installation steps are documented.

**Comment by keiem** [comment]
Ok, thanks.  I was also thinking about creating an overlay as the SDK for the pocketgo S30 is very minimal and old.  Keep up the good work.

**Comment by alpgarcia** [comment]
Closing as solved.
